apiVersion: certmanager.k8s.io/v1alpha2
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
spec:
 acme:
   email: eddie@vels.online
   http01: {}
   privateKeySecretRef:
     name: letsencrypt-prod
   server: https://acme-v02.api.letsencrypt.org/directory
